### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Nikoh77** [wilecoyote2015/darktabe_lut_generator#3]
During installation I have this error:
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
![Schermata a 2024-09-26 00-54-31](https://github.com/user-attachments/assets/03d2b9c0-807f-4fc8-9e03-8af1d84f5cc7)

Hi, please fix it, I just discovered this module and I can't wait to use it, I was looking for a solution like this for a long time...

**Comment by wilecoyote2015** [comment]
Hi, thanks for the report! Should be fixed now.

**Comment by Nikoh77** [comment]
Unfortunately not resolved:
![Schermata a 2024-09-27 14-06-51](https://github.com/user-attachments/assets/8622f989-2ac7-4119-9c4a-1877a3d30f8f)

**Comment by wilecoyote2015** [comment]
I see, there was an error in deployment. Now, it should really work (tested this)...

**Comment by Nikoh77** [comment]
Yes now it installation work fine.

**Comment by Nikoh77** [comment]
Using DLG i see:
`(venv) nikoh@nikoh-desktop:~/Scrivania/test_lut/darktabe_lut_generator$ darktable_lut_generator ../test/ ./test1.cube
/home/nikoh/Scrivania/test_lut/darktabe_lut_generator/venv/lib/python3.10/site-packages/colour/utilities/verbose.py:265: ColourUsageWarning: "Matplotlib" related API features are not available: "No module named 'matplotlib'".
See the installation guide for more information: https://www.colour-science.org/installation-guide/
  warn(*args, **kwargs)  # noqa: B028
/tmp/tmpxcs6masz/conf
converting image _9270007.JPG
`
the program execution continues, but is matplotlib also necessary?
